@accessToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk4MzkyNDMsInN1YiI6ImE4MjQxNTQ3LTRjMTItNDk2YS1iYWRmLTVhMWZhMjU0OGJmYiIsInR5cGUiOiJBRE1JTiJ9.enr3-E8RdA9klltUvCrivrvXi186TKTd1JdVqLDxdSI
###

# Listar usuários
GET http://127.0.0.1:4000/users
Authorization: {{accessToken}}

###

# Verificar tipo
POST http://127.0.0.1:4000/users
Authorization: {{accessToken}}
Content-Type: application/json

{
    "name":"Gabriel Felipe",
    "email": "gabrielfelp@gmail.com",
    "type": "ADMIN",
    "password": "1234"
}
###

# Token
POST http://127.0.0.1:4000/auth/login
Authorization: {{accessToken}}
Content-Type: application/json

{
    "email": "gabriel.freitas8@estudante.ifms.edu.br",
    "password": "gabriel123"
}

###
# Atualizar usuário
PUT http://127.0.0.1:4000/users
Content-Type: application/json
Authorization: {{accessToken}}

{
    "name": "Gabriel Freitas",
    "email": "gabriel.freitas8@estudante.ifms.edu.br"
}
###

# Atualizar senha
PUT http://127.0.0.1:4000/users/password
Content-Type: application/json
Authorization: {{accessToken}}

{
    "current_password": "nova_senha_456",
    "new_password": "gabriel123"
}
###

# Buscar dados de usuários autenticados
GET http://127.0.0.1:4000/auth/me
Authorization: Bearer {{accessToken}}
Content-Type: application/json